// <auto-generated />
using System;
using Banco.Content;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Banco.Migrations
{
    [DbContext(typeof(FilmeDBContext))]
    partial class FilmeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Negocio.Model.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("film_id")
                        .UseIdentityColumn();

                    b.Property<string>("AnoLancamento")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("release_year");

                    b.Property<string>("Classificacao")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("rating");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short?>("DuracaoEmMinutos")
                        .HasColumnType("smallint")
                        .HasColumnName("length");

                    b.Property<byte>("IdIdiomaDublagem")
                        .HasColumnType("tinyint")
                        .HasColumnName("language_id");

                    b.Property<byte?>("IdIdiomaOriginal")
                        .HasColumnType("tinyint")
                        .HasColumnName("original_language_id");

                    b.Property<byte[]>("ImagemCapa")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("cover_image");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("last_update")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.ToTable("film");
                });
#pragma warning restore 612, 618
        }
    }
}
